feat/product-page
nafikov/fake-burrberry-frontend pull request #1
Opened 2017-08-01 06:31 UTC by nafikov

2017-08-01 18:05 UTC, evgenyrodionov commented
Коммиты говно, читай телеграф

2017-08-01 18:06 UTC, imevro requested changes
https://rawgit.com/nafikov/fake-burrberry-frontend/feat/product-page/index.html

обнови плз под новый макет

кстати, у тебя кодстайл не соблюдается — 4 пробела вместо двух
плюс говнина с style, так нельзя
плюс шрифты через @import, так запрещено, есть link

читай codeguide.co короче

2017-08-03 11:30 UTC, evgenyrodionov commented
блядь да что у тебя с коммитами

2017-08-03 11:32 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28919983-851f6172-7858-11e7-984f-cd48aa6977ab.png)

2017-08-03 20:13 UTC, nafikov commented
Привет, сделал уже хорошо. Установил пиксель перфект плагин, с ним работа в разы ускорилась. Замучался до этого с зеплином. Буду очень благодарен, если проверишь в 12 вечера. Так как к 8 вечера не могу на проверку отправлять в связи работой, только вечером и утром могу исправлять.

2017-08-04 09:45 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28963706-c177ab74-7912-11e7-8ca7-a0bdfcf6024f.png)

2017-08-04 09:48 UTC, imevro requested changes
- кодстайл в хтмл
- нейминг слишком общий
- a11y
- кнопки
- иконки в разметке
- проблемы в описании
- слишком большая вложенность
- смешивание своих классов и классов сетки

2017-08-04 09:48 UTC, evgenyrodionov commented on .idea/codeStyleSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
убери этот мусор из репозитория

2017-08-04 20:19 UTC, nafikov commented
Пофиксил мобильную версию. Если возможно, проверь вечером пожалуйста.   Так как к 20-00 не могу делать из-за работы

2017-08-19 19:59 UTC, closed without merging