feat/product-page-adaptive
nafikov/fake-burrberry-frontend pull request #2
Opened 2017-08-05 08:51 UTC by nafikov

2017-08-05 15:14 UTC, evgenyrodionov commented
Не коммить после запроса ревью — я не понимаю могу ли я проверять или нет

2017-08-05 15:15 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28996478-fed6ea0a-7a09-11e7-9107-a6d71966e23f.png)

2017-08-05 15:15 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28996482-0847cc9e-7a0a-11e7-8980-b885afcebb5f.png)

2017-08-05 22:51 UTC, nafikov commented
сделал упор на адаптивность, из-за контейнера немного распидорило на мобайл. Прошу понять и простить)

2017-08-06 05:42 UTC, sparrow90 commented
![screencapture-001](https://user-images.githubusercontent.com/26340749/29000889-b3bef5b6-7a82-11e7-9a5e-c24d3e99826e.png)
![2017-08-06_083743](https://user-images.githubusercontent.com/26340749/29000888-b3bed450-7a82-11e7-9d8d-5ff05b391824.png)
![2017-08-06_083751](https://user-images.githubusercontent.com/26340749/29000890-b3c6bf30-7a82-11e7-9664-8f3266a74cfb.png)

Блин. На локале сетка хорошо работает, а вот сейчас посмотрел в rawgit  и ужаснулся.

2017-08-06 07:35 UTC, nafikov commented
- Адаптивность. Переписывался с ребятами, у кого-то норм работает, у кого-то нет. С локала все отлично. Пока не смог обнаружить причину такого непостоянного поведения. Если с гитроу будет криво, посмотри пожалуйста со своего локала (архив приложил)
[fake-burrberry-frontend.zip](https://github.com/nafikov/fake-burrberry-frontend/files/1202939/fake-burrberry-frontend.zip)

2017-08-06 08:03 UTC, nafikov commented
UPD: залил на github.io, там правильно работает. 
[https://sparrow90.github.io/]

У картинок скролл убран и стоит overflow-x: auto, чтобы по макету все было. Можно скроллить в мобильном режиме.

2017-08-06 21:43 UTC, imevro requested changes

2017-08-06 21:43 UTC, evgenyrodionov commented on index.html
> +              <li class="delivery__prop">
юл ли только для списков в тексте

2017-08-06 21:43 UTC, evgenyrodionov commented on index.html
> +          <a class="footer__menu-item" href="#">Contact Us</a>
в нав оберни

2017-08-06 21:43 UTC, evgenyrodionov commented on css/style.css
> +    height: 576px;
не задавай фиксированные размеры для картинок

2017-08-06 21:43 UTC, evgenyrodionov commented on css/style.css
> +    margin-left: -1px;
что за костыль

2017-08-06 21:43 UTC, evgenyrodionov commented on css/style.css
> +    padding-right: 0.35rem;
не изобретай костыли, очевидно же что это баг макета

2017-08-06 21:43 UTC, evgenyrodionov commented on css/style.css
> +.product__descr-title-lineheight {
lineheight? что за тупое название класса?

2017-08-06 21:43 UTC, evgenyrodionov commented on css/style.css
> +  height: 324px;
не ставь фикс

2017-08-06 21:43 UTC, evgenyrodionov commented on index.html
> +            <h1 class="product__info-price">110 000 руб</h1>
с хуя ли h1? h1 один на всю страницу

2017-08-06 21:43 UTC, evgenyrodionov commented on index.html
> +            <button class="product__color-btn bg-color-black" type="button" title="color: Black"></button>
где контент внутри кнопки?

2017-08-07 17:44 UTC, merged