feat/product-page-react
nafikov/fake-burrberry-frontend pull request #6
Opened 2017-08-12 17:07 UTC by nafikov

2017-08-12 19:25 UTC, evgenyrodionov commented
понятия не имею можно ли проверять если есть коммиты после запроса ревью

2017-08-13 06:36 UTC, nafikov commented
Классами не пользовался, пока не очень понимаю в них.

2017-08-14 10:41 UTC, imevro requested changes

2017-08-14 10:41 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
ну и чо

2017-08-14 10:41 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
ну и чо

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Footer/Navigation.js
> +const Item = styled.a`
ну и чо

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/MainInfo/GalleryLg.js
> +              margin6
nth-child

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/MainInfo/Header.js
> +export default props =>
смысл от этой прокладки, экспорти сразу ск

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/MainInfo/index.js
> +import GalleryXsMd from "./GalleryXsMd";
что это за плохой нейминг

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/MainInfo/index.js
> +import GalleryXsMd from "./GalleryXsMd";
Галерее должно быть похуй где она используется

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/Recommend/index.js
> +const productList = [
можно просто products, спасибо

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/Recommend/index.js
> +    price: "27 000"
числом + react-intl

2017-08-14 10:41 UTC, evgenyrodionov commented on src/Product/Recommend/index.js
> +    h2 {
что это за хуйня

2017-08-15 10:04 UTC, imevro approved these changes

2017-08-15 10:05 UTC, merged