feat/ci
nafikov/fake-burrberry-frontend pull request #8
Opened 2017-08-16 07:22 UTC by sparrow90

2017-08-16 07:24 UTC, nafikov commented
Eslint это жесть, часов 7 с ним воевал)

2017-08-16 10:13 UTC, evgenyrodionov commented
У тебя билд не проходит

2017-08-17 11:10 UTC, imevro requested changes
и зачем ты удалил сервисворкер?

2017-08-17 11:10 UTC, evgenyrodionov commented on .eslintrc.json
> +    "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }]
а зачем?

2017-08-17 11:10 UTC, evgenyrodionov commented on package.json
> +    "global": "^4.3.2",
а зачем?

2017-08-18 15:40 UTC, imevro approved these changes

2017-08-18 15:40 UTC, merged